# Generated by Django 3.0.8 on 2020-08-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_accounts', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
