# Generated by Django 3.0.8 on 2020-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('product', models.ManyToManyField(blank=True, to='eshop_products.Product', verbose_name='Products')),
            ],
        ),
    ]
