# Generated by Django 3.0.8 on 2020-08-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
